---
deployment:
  tasks:
    - /bin/rsync -av --delete --exclude=".env" ./ /home8/attoexaso/shurokkha.attoexasolutions.com/
    - cd /home8/attoexaso/shurokkha.attoexasolutions.com/
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
