---
deployment:
  tasks:
    - echo "START DEPLOY"
    - cp -r * /home8/attoexaso/shurokkha.attoexasolutions.com/
    - cd /home8/attoexaso/shurokkha.attoexasolutions.com/
    - /usr/local/bin/composer install --no-dev --optimize-autoloader
    - /usr/local/bin/php artisan optimize:clear
    - /usr/local/bin/php artisan optimize
