deployment:
  tasks:
    - /bin/rsync -av --delete --exclude=".env" ./ /home8/attoexaso/shurokkha.attoexasolutions.com/
    - cd /home8/attoexaso/shurokkha.attoexasolutions.com/
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
